#!/bin/bash
set -e

mysql --protocol=socket -uroot -p"${MYSQL_ROOT_PASSWORD}" <<EOSQL
CREATE DATABASE IF NOT EXISTS finance_users;
CREATE DATABASE IF NOT EXISTS finance_debt;
CREATE DATABASE IF NOT EXISTS finance_savings;
CREATE DATABASE IF NOT EXISTS finance_retirement;
CREATE DATABASE IF NOT EXISTS finance_analytics;

CREATE USER IF NOT EXISTS '${FINANCE_DB_USER}'@'%' IDENTIFIED BY '${FINANCE_DB_PASSWORD}';
ALTER USER '${FINANCE_DB_USER}'@'%' IDENTIFIED BY '${FINANCE_DB_PASSWORD}';
GRANT ALL PRIVILEGES ON finance_users.* TO '${FINANCE_DB_USER}'@'%';
GRANT ALL PRIVILEGES ON finance_debt.* TO '${FINANCE_DB_USER}'@'%';
GRANT ALL PRIVILEGES ON finance_savings.* TO '${FINANCE_DB_USER}'@'%';
GRANT ALL PRIVILEGES ON finance_retirement.* TO '${FINANCE_DB_USER}'@'%';
GRANT ALL PRIVILEGES ON finance_analytics.* TO '${FINANCE_DB_USER}'@'%';
FLUSH PRIVILEGES;
EOSQL
